### PR TITLE
Fix maxcitenames within fullfootcite

### PR DESCRIPTION
**Pull request by koep**
This commit fixes the fullfootcite command. "et al." is only supposed to be used when there are more than two authors.

Before:
```
    Vgl.: Porter, Michael E et al. (2006), S. 1337.
```
After:
```
    Vgl.: Porter, Michael E; Mark R Kramer (2006), S. 1337.
```

### CODE REVIEW

**Comment by koep** [comment]
I have to look into why this doesn't compile on travis.

**Comment by andygrunwald** [comment]
It seems that the error is not related to your PR.
Maybe it is the same as in https://github.com/andygrunwald/FOM-LaTeX-Template/issues/30

**Comment by koep** [comment]
I'm not sure why, but this patch fixes it for me :smiley:. (I compiled with docker-compile.sh).
I can't say if this has any impact on #30 or triggers any regressions though.

**Comment by koep** [comment]
I think this messes up some other stuff - closing for now.

**Pull request closed without merging**
